### ISSUE TITLE
모듈제작 - 플렉스 에디터

### ISSUE THREAD

**Issue by ParkDalJae** [kongukjae/KDT-2-Project-C-1#10]
플렉스 에디터
함수 명은 kingGodFlexEditor
매개변수로는 parent, flexDirection, alignItems, justifyContent, callback

parent = 부모
parent.style.display = flex   => 고정 속성, 매개변수는 없음.
flexDirection = column(세로), row(가로) 선택
alignItems  = 세로정렬
justifyContent = 가로정렬
callback = 콜백, 내용 없을시 매개변수 입력 X

제작은 모듈로 진행 될 예정이며
ESM모듈 기준으로 익스포트까지 완료 할 것.
※모듈 제작건에 대하여 추가 변경사항 발생시 댓글로 남길 것.

**Comment by skybluejean** [comment]
checked issue by ellen
