### ISSUE TITLE
#27 번 레시피 뷰, 등록페이지 이어서 제작

### ISSUE THREAD

**Issue by ParkDalJae** [kongukjae/KDT-2-Project-C-1#45]
내용 채우기
기존이슈 닫은 이유
새 이슈 작성 할 내용 혹은 작업 할 내용

**Comment by skybluejean** [comment]
내용 : 이 45번 이슈는 기존 27번 이슈에서 버튼구현까지 만들어놓고 뒷내용을 마저 이어서 하는 부분임
기존이슈 닫은 이유 : 레시피 뷰와 레시피 등록 페이지를 만들면서 기본적인 레이아웃 툴을 만들어내는데까지 마무리하여 여기서 태그라던지 그밖의 다른 기능들을 추가 및 수정할것을 염려하여 새 이슈를 만듬
새 이슈에서 작성(작업) 할 내용 : 기존에 임의로 만들어진 레이아웃 툴에서 이미지 파일 업로드 및 input기능 추가 및 구현을 작업
