### ISSUE TITLE
API 검색 기반 재료 parsing

### ISSUE THREAD

**Issue by ParkDalJae** [kongukjae/KDT-2-Project-C-1#56]

**Comment by pflying1** [comment]
1. DB에 저장되어 있는 recipe_ingredients_table을 json파일로 가져온다 
2. ingredients컬럼 가져와서 재료이름만 빼와서 저장하기

**Comment by pflying1** [comment]
1. processed_api_ingredients.js
reicpe_ingredients_table 에 있는 regist_ingredients 컬럼 데이터를  다시한번 재료 이름만 남기고 다시 한번 가공
2. processed_data_ingredients_table.json
위 1번 실행시 저장되는 json 데이터
3. processed_ingredients_table_data.js
mysql에 데이터를 넣는 쿼리문 작성

**Comment by pflying1** [comment]
4.processed_api_ingredients_second.js
 중복제거 + 공백제거 한후 하나의 배열로 저장
5. main 에 merge후  issue close
