### ISSUE TITLE
모듈제작 - 태그메이커

### ISSUE THREAD

**Issue by ParkDalJae** [kongukjae/KDT-2-Project-C-1#7]
1. 태그 생성기.
2. 함수 명은 multiAndSingleTagMaker
3. 매개변수로는 parent, element, id, length, callback
4. parent = 부모
5. element = 태그 속성
6. id = 
- a : undefined 아이디 없음 => 매개변수 공란
- b : string => 단일 객체 생성시 매개변수 문자열
- c : [] => 배열만 for문 돌릴때 쓰는건데 근데 갯수를 적으면 그만큼에 생성이 되면서 id를 입력해주는거죠
- d : {} => 객체 안의 갯수(키 : 값)에 따라서 setAttribute의 속성이 한개의 태그 안에서 추가됨
7. length = 반복횟수, 기본값 1
8. callback = 콜백, 내용없을시 매개변수 입력 X
9. 제작은 모듈로 진행 될 예정이며
10. ESM모듈 기준으로 익스포트까지 완료 할 것.

※모듈 제작건에 대하여 추가 변경사항 발생시 댓글로 남길 것.

**Comment by dltpals222** [comment]
1. undefined는 id에 기본값으로 ""을 줌으로써 제외시킴
2. string에서 ""가 올 경우 id없는 tag가 만들어짐
3. string 혹은 number가 올 경우로 교체
4. 배열이 하나 일 경우 string&number와 같은 작동을 함
5. 배열이 여러개인 경우 callback과 return이 없음
6. 객체에 여러개를 넣을 경우 키는 속성이 된다.
7. 제일 먼저 인식되는 것은 length로 설정했다.

**Comment by dltpals222** [comment]
1. 제일 먼저 인식되는 것은 length이므로 2 이상일 경우 tagName으로 지정된 태그를 갯수대로 만듦
2. length는 기본값이 1이므로 빈칸으로 놓더라도 1로 설정됨
3. id는 총 4가지로 설정된다. 
4. id는 기본값으로 ""설정되어있다. (type은 string이다)
5. id에 string과 number 입력
6. id에 배열을 입력 -> 배열이 1개인 경우 5번과 같은 동작을 한다.
7. id에 배열을 입력 -> 배열이 2개 이상인 경우 loop로 동작되며 여기서는 callback과 return이 없다.
8. id에 객체를 입력 -> 객체의 키가 속성(id, class 등과 같은)이 되며 하나의 태그에 여러개의 속성이 만들어진다.
