### ISSUE TITLE
모듈제작 - 레이아웃 에디터

### ISSUE THREAD

**Issue by ParkDalJae** [kongukjae/KDT-2-Project-C-1#8]
1. 레이아웃 에디터
2. 함수 명은 fontAndLayoutEditor
3. 매개변수로는 parent,width, height, border, backgroundColor, font, callback

5. parent = 부모
6. width = 가로
7. height = 세로
8. border = 1.기본 스타일 3개 지정. 
                   2.별도 스타일 지정시 문자열 입력 가능
10. font =  1. 숫자 입력시 기본 폰트사이즈 변경
                  2. 객체, 폰트스타일 등이 지정된 객체 입력 시 해당 객체의 프로퍼티로 적용 가능
11. callback = 콜백               

제작은 모듈로 진행 될 예정이며
ESM모듈 기준으로 익스포트까지 완료 할 것.
※모듈 제작건에 대하여 추가 변경사항 발생시 댓글로 남길 것.

**Comment by pflying1** [comment]
border 값을 "1"로주면 "1px solid black" 
원하는 폰트 스타일 바꾸고 싶을때 직접 객체를 만들 것
객체 만드는 예시
ex) const fontStyle = { fontSize: "30px", color: "white" };
