### ISSUE TITLE
모듈제작 - 포지션 에디터

### ISSUE THREAD

**Issue by ParkDalJae** [kongukjae/KDT-2-Project-C-1#9]
포지션 에디터
함수 명은 superGreatPositionEditor
매개변수로는 parent, position, top, bottom , left, right, zIndex, callback

parent = 부모
position = 포지션
top = 탑
bottom = 바텀
left = 레프트
right = 라이트
callback = 콜백, 내용 없을시 매개변수 입력 X

제작은 모듈로 진행 될 예정이며
ESM모듈 기준으로 익스포트까지 완료 할 것.
※모듈 제작건에 대하여 추가 변경사항 발생시 댓글로 남길 것.

**Comment by KyoungTaekLee** [comment]
완료.
top, bottom, left, right 는 객체로 선언하도록 object로 묶어서 작성했음.

**Comment by KyoungTaekLee** [comment]
// 요소에 position 속성을 부여하는 함수
// top, bottom, left, right는 object 아래의 변수의 값에 해당
// 그러므로 top, bottom, left, right에 value를 부여하려면
// 해당 변수들을 사용해야 한다.
